name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release PR or publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Fetch all Git history so that Changesets can generate changelogs
          # with the correct commits
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Create release PR or publish to NPM
        uses: changesets/action@master
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
