name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create release PR or publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment with pnpm
        uses: danoc/pnpm-setup-composite-action@v2
        with:
          checkout-fetch-depth: '0'
      - name: Create release PR or publish to NPM
        uses: changesets/action@master
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
