name: Test

on: [push]

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment with pnpm
        uses: danoc/pnpm-setup-composite-action@v1
      - name: Run Jest
        run: pnpm run test:jest
  tslint:
    name: TSLint
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment with pnpm
        uses: danoc/pnpm-setup-composite-action@v1
      - name: Run TSLint
        run: pnpm run test:tslint
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment with pnpm
        uses: danoc/pnpm-setup-composite-action@v1
      - name: Run Prettier
        run: pnpm run test:prettier
